version: 2
jobs:
  build:
    docker:
      - image: tonyodell/rakudo-nightly:latest

    working_directory: ~

    steps:
      - checkout
      - run: 
          name: install build deps
          command: |
              zef install --deps-only .
      - run:
          name: test 
          command: |
              zef test .
      - run:
          name: publish
          command: |
              if [[ "$CIRCLE_BRANCH" = "circle-tests" ]]; then
                # this will fail to index
                raku -Ilib -e 'require ::("Fez::CLI"); our $*USERNAME = %*ENV<FEZ_UN>; say "username: \"{$*USERNAME}\""; our $*PASSWORD = %*ENV<FEZ_PW>; ::("Fez::CLI")::<&MAIN>("upload");';
                echo "rc: $?"
              else
                echo 'publish only master!'
              fi
