version: 2
jobs:
  build:
    docker:
      - image: tonyodell/rakudo-nightly:latest

    working_directory: ~

    steps:
      - checkout
      - run: 
          name: install build deps
          command: |
              zef install --deps-only .
      - run:
          name: test 
          command: |
              zef test .
      - run:
          name: publish
          command: |
              git rev-parse --abbrev-ref HEAD
              if [[ "$CIRCLE_BRANCH" = "circle-tests" ]]; then
                exit 1
              fi
